<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251217141843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE route_segment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distance DOUBLE PRECISION NOT NULL, start_station_id INT NOT NULL, end_station_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0D2A8FD53721DCB ON route_segment (start_station_id)');
        $this->addSql('CREATE INDEX IDX_E0D2A8FD2FF5EABB ON route_segment (end_station_id)');
        $this->addSql('CREATE TABLE station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, longname VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE route_segment ADD CONSTRAINT FK_E0D2A8FD53721DCB FOREIGN KEY (start_station_id) REFERENCES station (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE route_segment ADD CONSTRAINT FK_E0D2A8FD2FF5EABB FOREIGN KEY (end_station_id) REFERENCES station (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE route_segment DROP CONSTRAINT FK_E0D2A8FD53721DCB');
        $this->addSql('ALTER TABLE route_segment DROP CONSTRAINT FK_E0D2A8FD2FF5EABB');
        $this->addSql('DROP TABLE route_segment');
        $this->addSql('DROP TABLE station');
    }
}
